### ISSUE TITLE
The latest version of az cli (2.30.0) break while running az commands

### ISSUE THREAD

**Issue by tranguyen221** [microsoft/dstoolkit-mlops-base#47]
azure-cli 2.30.0 throws ERROR: {'Error': TypeError("__init__() got an unexpected keyword argument 'async_persist'",)} while running the pipeline: dstoolkit-mlops-base/invoke-aml-pipeline.template.yml at main · microsoft/dstoolkit-mlops-base (github.com)

As a workaround, we found that the az cli 2.30.0 will install azure-cli-ml version 1.5.0 as default
{
    "experimental": false,
    "extensionType": "whl",
    "name": "azure-cli-ml",
    "path": "/opt/az/azcliextensions/azure-cli-ml",
    "preview": false,
    "version": "1.5.0"
  }
We need to downgrade the azure-cli 2.29.2 and the azure-cli-ml version 1.33.1 is installed correctly.

**Comment by mariamedp** [comment]
Original issue for reference: https://github.com/Azure/azure-cli/issues/20297

**Comment by tranguyen221** [comment]
Change pool version from ubuntu-latest to ubuntu-18.04 because of this error:
```
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dotnetcore2/runtime.py", line 279, in attempt_get_deps

raise NotImplementedError(err_msg + '\n' + _unsupported_help_msg)

NotImplementedError: Linux distribution ubuntu 20.04 does not have automatic support.

.NET Core 2.1 can still be used via dotnetcore2 if the required dependencies are installed.

Visit https://aka.ms/dotnet-install-linux for Linux distro specific .NET Core install instructions.

Follow your distro specific instructions to install `dotnet-runtime-*` and replace `*` with `2.1`.
```

**Comment by tranguyen221** [comment]
Downgrade the azure-devops 0.21.0 due to this error:

```
The 'azure-devops' extension version 0.22.0 is not compatible with your current CLI core version 2.29.2.

This extension requires a min of 2.30.0 CLI core.
```

**Comment by mariamedp** [comment]
The most recent SDK version (1.43.0) [fixes this](https://docs.microsoft.com/en-us/azure/machine-learning/azure-machine-learning-release-notes#2022-06-27):
> ADAL authentication is now deprecated and all authentication classes now use MSAL authentication. Please install azure-cli>=2.30.0 to utilize MSAL based authentication when using AzureCliAuthentication class.

We can now try reverting back to unpinned versions
